function [fitresult, gof] = createFit(X, Y, zz)
%CREATEFIT(X,Y,ZZ)
%  Create a fit.
%
%  Data for 'Gauss' fit:
%      X Input : X
%      Y Input : Y
%      Z Output: zz
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 20-Jul-2018 15:36:05


%% Fit: 'Gauss'.
[xData, yData, zData] = prepareSurfaceData( X, Y, zz );

% Set up fittype and options.
ft = fittype( 'a * exp( -(X - b)^2 / (2 * c^2) ) * exp( -(Y - d)^2 / (2 * f^2) )', 'independent', {'X', 'Y'}, 'dependent', 'z' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.317014352285803 0.320459648231451 0.510015219882756 0.831359756387049 0.034833820567729];

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Gauss' );
h = plot( fitresult, [xData, yData], zData );
k = plot( fitresult );
legend( h, 'Gauss', 'zz vs. X, Y', 'Location', 'NorthEast' );
% Label axes
xlabel X
ylabel Y
zlabel zz
grid on
view( -29.5, 33.2 );

end
