function z = fittie3d(par, X, Y)

% Construct a 3d Gaussian array from 7 parameters (incl a rotation term), 
% and X + Y arrays

z = par(7) + par(1) * exp(...
    -(( ...
    (X-par(5)).*cosd(par(2)) + (Y-par(6)).*sind(par(2)) ...
            ) ./par(3) ).^2 ...
    -(( ...
    -(X-par(5)).*sind(par(2)) + (Y-par(6)).*cosd(par(2)) ...
            ) ./par(4) ).^2);

fprintf(['A 3D Gaussian with xwidth %.3f, ywidth %.3f;\n\t'...
    'height %.3f; centered at (%.1f,%.1f) at an angle of %.1f degrees.\n'], ...
        par(3), par(4), par(1), par(5), par(6), par(2));
        
end